name: Azure Bicep

on: [push]
# on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

env:
  AZURE_DEPLOYMENT_NAME: "azurewifi"
  AZURE_DEPLOYMENT_REGION: "australiaeast"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Run Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        allow-no-subscriptions: true

    - name: Run Azure Bicep Deploy
      uses: azure/CLI@v2
      with:
        inlineScript: |
          az config set bicep.use_binary_from_path=False
          az bicep install
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az deployment sub create -f ./main.bicep -n ${{ env.AZURE_DEPLOYMENT_NAME }} -l ${{ env.AZURE_DEPLOYMENT_REGION }} -p token=${{ secrets.GIT_HUB_CREDENTIALS }} password=${{ secrets.ADMIN_CREDENTIALS }}
